version: '2'

services:
  db:
    container_name: blog_db
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blog
      MYSQL_USER: blog
      MYSQL_PASSWORD: secret

  php:
    container_name: blog_php
    build:
      context: ./dockerfiles/php
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    ports:
      - 80:80
    volumes:
      - ./../:/var/www/html
    links:
      - db